version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: npm
    versions:
    - 7.10.0
    - 7.11.0
    - 7.5.3
    - 7.6.2
    - 7.7.0
    - 7.7.4
    - 7.7.5
    - 7.7.6
    - 7.8.0
    - 7.9.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: compile-sass
    versions:
    - 1.1.2
